#!/usr/bin/env bash
set -euo pipefail

# =========================
# OpenConnect Server (ocserv) installer from source
# Debian-focused, TCP-only AnyConnect on 443
# =========================

OCSERV_VER_DEFAULT="1.2.2"
VPN_NET_DEFAULT="192.168.100.0"
VPN_MASK_DEFAULT="255.255.255.0"
VPN_CIDR_DEFAULT="192.168.100.0/24"
TCP_PORT_DEFAULT="443"

CONFIG_DIR="/usr/local/etc/ocserv"
CONFIG_FILE="${CONFIG_DIR}/ocserv.conf"
PASSWD_FILE="${CONFIG_DIR}/ocpasswd"

SERVICE_FILE="/etc/systemd/system/ocserv.service"
SYSCTL_FILE="/etc/sysctl.d/99-ocserv-forward.conf"

RUN_DIR="/run/ocserv"

log() { echo -e "[+] $*"; }
warn() { echo -e "[!] $*" >&2; }
die() { echo -e "[-] $*" >&2; exit 1; }

need_root() {
  [[ "${EUID}" -eq 0 ]] || die "Run as root (sudo)."
}

usage() {
  cat <<EOF
Usage:
  $0 --domain <domain> --user <username> [options]

Required:
  --domain  <domain>      e.g. os.cs7.ir  (must exist under /etc/letsencrypt/live/<domain>/)
  --user    <username>    e.g. vpn

Optional:
  --port    <tcp_port>    default: ${TCP_PORT_DEFAULT}
  --net     <ipv4_net>    default: ${VPN_NET_DEFAULT}
  --mask    <ipv4_mask>   default: ${VPN_MASK_DEFAULT}
  --cidr    <ipv4_cidr>   default: ${VPN_CIDR_DEFAULT}
  --iface   <iface>       outbound interface (auto-detected if omitted)
  --version <ver>         ocserv version default: ${OCSERV_VER_DEFAULT}
  --persist-iptables      install iptables-persistent + save rules
  --force                stop if port 443 is used? (force will NOT stop services; just skip the check)

Example:
  $0 --domain os.cs7.ir --user vpn --persist-iptables
EOF
}

detect_iface() {
  # Default route interface
  ip route get 1.1.1.1 2>/dev/null | awk '/dev/ {for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}'
}

port_in_use_by() {
  local port="$1"
  # prints process line if in use, empty if free
  ss -lntp 2>/dev/null | awk -v p=":${port}" '$4 ~ p {print}'
}

ensure_packages() {
  log "Installing dependencies..."
  apt update -y
  apt install -y --no-install-recommends \
    ca-certificates wget build-essential pkg-config \
    iproute2 iptables \
    libgnutls28-dev libev-dev libpam0g-dev \
    liblz4-dev libseccomp-dev libreadline-dev \
    libnl-route-3-dev
}

build_install_ocserv() {
  local ver="$1"
  log "Downloading ocserv ${ver}..."
  cd /root
  wget -q "https://www.infradead.org/ocserv/download/ocserv-${ver}.tar.xz" -O "ocserv-${ver}.tar.xz"
  rm -rf "/root/ocserv-${ver}" || true
  tar -xf "ocserv-${ver}.tar.xz"
  cd "ocserv-${ver}"

  log "Configuring..."
  ./configure >/dev/null

  log "Building..."
  make -j"$(nproc)" >/dev/null

  log "Installing to /usr/local..."
  make install >/dev/null

  command -v /usr/local/sbin/ocserv >/dev/null || die "ocserv not found after install."
  log "ocserv version: $(/usr/local/sbin/ocserv --version | head -n1)"
}

write_config() {
  local domain="$1"
  local tcp_port="$2"
  local vpn_net="$3"
  local vpn_mask="$4"
  local vpn_cidr="$5"

  local cert="/etc/letsencrypt/live/${domain}/fullchain.pem"
  local key="/etc/letsencrypt/live/${domain}/privkey.pem"

  [[ -f "${cert}" ]] || die "Cert not found: ${cert}"
  [[ -f "${key}"  ]] || die "Key not found:  ${key}"

  mkdir -p "${CONFIG_DIR}"
  mkdir -p "${RUN_DIR}"

  if [[ -f "${CONFIG_FILE}" ]]; then
    cp -a "${CONFIG_FILE}" "${CONFIG_FILE}.bak.$(date +%F-%H%M%S)"
    log "Backed up old config to ${CONFIG_FILE}.bak.*"
  fi

  log "Writing ocserv config: ${CONFIG_FILE}"
  cat > "${CONFIG_FILE}" <<EOF
# ocserv config (TCP only, password auth, AnyConnect compatible)
# Generated by setup script

tcp-port = ${tcp_port}
udp-port = 0

auth = "plain[${PASSWD_FILE}]"

server-cert = ${cert}
server-key  = ${key}

# Mandatory runtime options
run-as-user = nobody
run-as-group = nogroup
socket-file = ${RUN_DIR}/ocserv.sock
pid-file = ${RUN_DIR}/ocserv.pid
device = ocvpn

# VPN network
ipv4-network = ${vpn_net}
ipv4-netmask = ${vpn_mask}

# Full tunnel
route = default

# DNS pushed to clients
dns = 1.1.1.1
dns = 8.8.8.8

# Keepalive
keepalive = 300
dpd = 90
mobile-dpd = 180

log-level = 1
EOF

  # sanity check config references
  grep -nE '^(tcp-port|udp-port|auth|server-cert|server-key|socket-file|pid-file|device|ipv4-network|route|dns)' "${CONFIG_FILE}" >/dev/null
}

create_user() {
  local user="$1"
  mkdir -p "${CONFIG_DIR}"
  log "Creating/updating user '${user}' in ${PASSWD_FILE}"
  /usr/local/bin/ocpasswd -c "${PASSWD_FILE}" "${user}"
  chmod 600 "${PASSWD_FILE}"
}

enable_ip_forward() {
  log "Enabling IPv4 forwarding (persistent)..."
  cat > "${SYSCTL_FILE}" <<EOF
net.ipv4.ip_forward=1
EOF
  sysctl --system >/dev/null
  local v
  v="$(cat /proc/sys/net/ipv4/ip_forward || true)"
  [[ "${v}" == "1" ]] || die "ip_forward did not become 1 (got: ${v})"
  log "ip_forward=1"
}

apply_iptables() {
  local tcp_port="$1"
  local vpn_cidr="$2"
  local iface="$3"

  log "Applying iptables rules (INPUT ${tcp_port}/tcp, FORWARD, NAT via ${iface})..."

  # INPUT allow 443/tcp
  iptables -C INPUT -p tcp --dport "${tcp_port}" -j ACCEPT 2>/dev/null || \
    iptables -A INPUT -p tcp --dport "${tcp_port}" -j ACCEPT

  # FORWARD allow vpn subnet both directions
  iptables -C FORWARD -s "${vpn_cidr}" -j ACCEPT 2>/dev/null || \
    iptables -A FORWARD -s "${vpn_cidr}" -j ACCEPT
  iptables -C FORWARD -d "${vpn_cidr}" -j ACCEPT 2>/dev/null || \
    iptables -A FORWARD -d "${vpn_cidr}" -j ACCEPT

  # NAT masquerade
  iptables -t nat -C POSTROUTING -s "${vpn_cidr}" -o "${iface}" -j MASQUERADE 2>/dev/null || \
    iptables -t nat -A POSTROUTING -s "${vpn_cidr}" -o "${iface}" -j MASQUERADE

  log "iptables OK"
}

install_systemd_service() {
  log "Writing systemd service: ${SERVICE_FILE}"
  cat > "${SERVICE_FILE}" <<EOF
[Unit]
Description=OpenConnect VPN Server (ocserv)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/sbin/ocserv -c ${CONFIG_FILE} -f
Restart=on-failure
RestartSec=2
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now ocserv
}

persist_iptables_rules() {
  log "Installing iptables-persistent and saving rules..."
  DEBIAN_FRONTEND=noninteractive apt install -y iptables-persistent >/dev/null || true
  if command -v netfilter-persistent >/dev/null; then
    netfilter-persistent save
  else
    warn "netfilter-persistent not found; rules may not persist."
  fi
}

# ===== Parse args =====
need_root

DOMAIN=""
VPN_USER=""
TCP_PORT="${TCP_PORT_DEFAULT}"
VPN_NET="${VPN_NET_DEFAULT}"
VPN_MASK="${VPN_MASK_DEFAULT}"
VPN_CIDR="${VPN_CIDR_DEFAULT}"
OCSERV_VER="${OCSERV_VER_DEFAULT}"
IFACE=""
PERSIST_IPTABLES="0"
FORCE="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="${2:-}"; shift 2;;
    --user) VPN_USER="${2:-}"; shift 2;;
    --port) TCP_PORT="${2:-}"; shift 2;;
    --net) VPN_NET="${2:-}"; shift 2;;
    --mask) VPN_MASK="${2:-}"; shift 2;;
    --cidr) VPN_CIDR="${2:-}"; shift 2;;
    --iface) IFACE="${2:-}"; shift 2;;
    --version) OCSERV_VER="${2:-}"; shift 2;;
    --persist-iptables) PERSIST_IPTABLES="1"; shift 1;;
    --force) FORCE="1"; shift 1;;
    -h|--help) usage; exit 0;;
    *) die "Unknown arg: $1 (use --help)";;
  esac
done

[[ -n "${DOMAIN}" ]] || { usage; die "Missing --domain"; }
[[ -n "${VPN_USER}" ]] || { usage; die "Missing --user"; }

# detect iface if not set
if [[ -z "${IFACE}" ]]; then
  IFACE="$(detect_iface)"
fi
[[ -n "${IFACE}" ]] || die "Could not detect outbound interface. Provide --iface <name>"

# check port availability
INUSE="$(port_in_use_by "${TCP_PORT}" || true)"
if [[ -n "${INUSE}" && "${FORCE}" != "1" ]]; then
  echo "${INUSE}"
  die "Port ${TCP_PORT} appears in use. Stop the other service or use different --port. (Or pass --force to skip this check.)"
fi

log "Domain: ${DOMAIN}"
log "User: ${VPN_USER}"
log "TCP port: ${TCP_PORT}"
log "VPN subnet: ${VPN_CIDR} (${VPN_NET} / ${VPN_MASK})"
log "Outbound interface: ${IFACE}"
log "ocserv version: ${OCSERV_VER}"

ensure_packages
build_install_ocserv "${OCSERV_VER}"
write_config "${DOMAIN}" "${TCP_PORT}" "${VPN_NET}" "${VPN_MASK}" "${VPN_CIDR}"
create_user "${VPN_USER}"
enable_ip_forward
apply_iptables "${TCP_PORT}" "${VPN_CIDR}" "${IFACE}"
install_systemd_service

if [[ "${PERSIST_IPTABLES}" == "1" ]]; then
  persist_iptables_rules
else
  warn "iptables rules are NOT persisted across reboot (add --persist-iptables if you want)."
fi

log "Final checks:"
systemctl --no-pager -l status ocserv || true
ss -lntp | grep ":${TCP_PORT}" || true

echo
log "DONE ✅"
echo "Connect with AnyConnect / OpenConnect:"
echo "  Server: https://${DOMAIN}"
echo "  Username: ${VPN_USER}"
echo "  Password: (the one you entered)"
echo
echo "If you connect but have no internet, send me outputs of:"
echo "  ip -br a"
echo "  iptables -t nat -S"
echo "  iptables -S FORWARD"